# Generated by Django 3.0.4 on 2020-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-infected']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['-infected']},
        ),
    ]
