# Generated by Django 3.0.2 on 2020-03-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_country_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='user',
            new_name='related_user',
        ),
    ]
